### ISSUE TITLE
Example of submitting a donation

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-example#26]
Add a link from the example page to a donation payment flow. This should be somewhat realistic in the sense that it passes the ID of whom should be receiving the donation (the "seller" in our current parlance).

Supports: https://github.com/mozilla/payments/issues/117

**Comment by andymckay** [comment]
Kinda got this in progress so I'll take that.

**Comment by andymckay-limited-access** [comment]
Doing this in #27.
