### ISSUE TITLE
Enable FxA sign-in on AWS (pay.dev.mozaws.net)

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-example#6]
We have a hosted dev site at http://pay.dev.mozaws.net/ but sign-in doesn't work because the FxA client ID is configured only for the domain `pay.dev`. Let's configure a new client ID for the AWS site. This can be done at https://oauth-stable.dev.lcip.org/console/clients

**Comment by andymckay-limited-access** [comment]
I think we'll need this to get any further on http://pay.dev.mozaws.net/

**Comment by muffinresearch** [comment]
I've got a patch that adds another clientID - presumably we're OK with continuing to just stick the example app secrets in the code?

**Comment by andymckay** [comment]
Sure, we could work on payments-config as per email to dev-payments :)

**Comment by muffinresearch** [comment]
The config in payments-example has been added. Going to close this and we should open new tickets if other things need doing.
